version: "3.8"
services:
  api:
    build:
      context: ./app
    volumes:
      - ./app/:/app/
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      MYSQL_USER: jlorxvrmqbgxrm
      MYSQL_PASSWORD: 55cb27765e7844b835a4e8eb4d718db7a876fe25e7c5b3345bb9dfde807e0b58
      MYSQL_HOST: ec2-54-164-138-85.compute-1.amazonaws.com:5432
      MYSQL_DATABASE: dalsgrvh02hklp
    healthcheck:
      test: "curl -f http://localhost:8000/ || exit 1"
      timeout: 45s
      interval: 5s
      retries: 20
